/*
 * THIS CLASS MANAGES ALL FILE HANDLING EVENTS
 * SAVING AND LOADING FILES
 * */

#ifndef YEAR1_CPP_PROJECT_FILEHANDLER_H
#define YEAR1_CPP_PROJECT_FILEHANDLER_H

class FileHandler {

};

#endif //YEAR1_CPP_PROJECT_FILEHANDLER_H
