/*
 * THIS CLASS MANAGES LOGGING OF EVENTS
 * CHILD CLASS OF EVERY OTHER CLASS
 * */

#ifndef YEAR1_CPP_PROJECT_LOGS_H
#define YEAR1_CPP_PROJECT_LOGS_H

class Logs {

};

#endif //YEAR1_CPP_PROJECT_LOGS_H
