/*
 * THIS CLASS MANAGES ORDERING OF ITEMS THAT THE SHOPPER HAS PICKED UP
 * ACTIVATED/USED WHEN SHOPPER LEAVES STORE AND CHARGES CARD ETC
 * */

#ifndef YEAR1_CPP_PROJECT_ORDER_H
#define YEAR1_CPP_PROJECT_ORDER_H

class Order {

};

#endif //YEAR1_CPP_PROJECT_ORDER_H
